/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'

const Home: NextPage = () => {
  return (
    <div className="bg-[#333333] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Byron's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />
      {/* hero banner */}
      <section id="hero" className="snap-center">
        <Hero />
      </section>
      {/* about */}
      {/* experience */}
      {/* skills */}
      {/* projects */}
      {/* contact me */}


    </div>
  )
}

export default Home
