name: CI/CD  # or whatever your workflow is named

on:
  push:
    branches: [ main ]  # or your default branch
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # This specifies Node.js 18
        
    - name: Install dependencies
      run: npm ci
    
    # ... rest of your workflow steps 