name: CI/CD  # or whatever your workflow is named

on:
  push:
    branches: [ main ]  # or your default branch
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'  # Updated from '18.x' to '20.x'
        
    - name: Install dependencies
      run: npm ci
    
    # ... rest of your workflow steps 