name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Delete old artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: github-pages
          failOnError: false

      - name: Clean install dependencies
        run: |
          # Remove existing lock file and node_modules
          rm -f package-lock.json
          rm -rf node_modules
          
          # Clean npm cache
          npm cache clean --force
          
          # Install dependencies and generate new lock file
          npm install
          
          # Remove problematic packages
          rm -rf node_modules/@next/swc-darwin-arm64
          rm -rf node_modules/@sentry/cli
          rm -rf node_modules/react-social-icons/.cache
          rm -rf sanity/node_modules

      - name: Build with Next.js
        run: |
          # Remove existing build artifacts
          rm -rf .next
          rm -rf out
          
          # Build the project
          npm run build
          
      - name: Prepare artifact
        run: |
          mkdir -p clean-out
          
          # Copy only essential files
          echo "Copying essential files..."
          cp -r out/_next/static/css clean-out/_next/static/ 2>/dev/null || true
          cp -r out/_next/static/media clean-out/_next/static/ 2>/dev/null || true
          cp -r out/assets clean-out/ 2>/dev/null || true
          cp -r out/images clean-out/ 2>/dev/null || true
          
          # Copy HTML and small JS files
          find out -name "*.html" -exec cp --parents {} clean-out/ \;
          find out/_next/static -name "*.js" -size -1M -exec cp --parents {} clean-out/ \;
          
          # Add .nojekyll
          touch clean-out/.nojekyll
          
          # Debug information
          echo "Final artifact contents and sizes:"
          du -sh clean-out/*
          find clean-out -type f -size +1M -exec echo "Large file: {}" \; -exec ls -lh {} \;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: clean-out
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
