name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true
          
      - name: Clean GitHub Actions cache
        run: |
          rm -rf ~/.cache/github-actions
          rm -rf ~/.npm
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
          cache: 'npm'
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
          
      - name: Install dependencies
        run: |
          echo "Current Node version: $(node -v)"
          echo "Current NPM version: $(npm -v)"
          npm cache clean --force
          rm -rf node_modules
          rm -f package-lock.json
          npm install --legacy-peer-deps
          
      - name: Build with Next.js
        run: |
          npm run build
          touch out/.nojekyll
          find out -type l -delete
          find out -type f -links +1 -delete
          chmod -R 755 out
          
      - name: Debug output directory
        run: |
          du -sh out/
          find out/ -type f -exec ls -l {} \;
          
      - name: Upload to GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: out
          retention-days: 1
          if-no-files-found: error
          compression-level: 9

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4